### PR TITLE
Update Vendor Namespace

### PR DESCRIPTION
**Pull request by cyrillkalita**
Update vendor namespace
Apply PSR-2 style

Closing #8

### CODE REVIEW

**Comment by cyrillkalita** [comment]
@mastani I have updated the namespace and ran the code through PSR-2 with phpcs.

Given the scope of changes I suggest next paradigm version

**Comment by mastani** [comment]
@cyrillkalita Take a look at #10 PR, Extracting the abstract classes looks like a good idea. But we still need the TitleCase vendor prefix.

**Comment by cyrillkalita** [comment]
@mastani do you want to add this project to StyleCI?

**Comment by cyrillkalita** [comment]
@mastani As a matter of fact, I just ran it though my StyleCI account, so we should be good style-wise.

**Comment by mastani** [comment]
Great @cyrillkalita, I will release a new version.
Thank you very much.

**Pull request merged**
